### ISSUE TITLE
Enable TUN module in kernel

### ISSUE THREAD

**Issue by ddewaele** [UDOOboard/linux_kernel#15]
Would be great if you could enable tunnelling support (as a module) in the kernel.

That way we could install OpenVPN out of the box without kernel change.

(http://udoo.org/forum/threads/need-kernel-source-for-tun-tap-openvpn.3042/)

**Comment by patrykk** [comment]
That same with gspca modules for webcam :)

**Comment by fmntf** [comment]
Fixed in 2f732dd2faef5f30b76ffe7a093df34986d7afd8 and d764b728236c357ec0417a1e89775d8cc3aa5574. The kernel will be rebuilt and pushed on the repository in the next days.

**Comment by ddewaele** [comment]
@fmntf : Great ... when are you planning a new udoo image that we can download from the site that will include this change ?

**Comment by fmntf** [comment]
@ektor5 just pushed the new package into our repository.
