### ISSUE TITLE
Help with VT1613

### ISSUE THREAD

**Issue by vpeter4** [UDOOboard/linux_kernel#2]
I'm seeking help with vt1613 driver. I ported almost all the changes to my 3.14.36 kernel which is heavily patched. The only difference is with file sound/soc/fsl/fsl_ssi.c where I could not copy all the changes. Anyway, here is relevant part from dmesg. If anyone has any idea where I have a problem please let me know.

``````
[    5.431054] imx-ac97-vt1613 sound.28: ASoC: CPU DAI 2028000.ssi not registered
[    5.431100] imx-ac97-vt1613 sound.28: snd_soc_register_card() failed: -517
[    5.431123] platform sound.28: Driver imx-ac97-vt1613 requests probe deferral
[    5.440689] imx-ac97-vt1613 sound.28: ASoC: CPU DAI 2028000.ssi not registered
[    5.440742] imx-ac97-vt1613 sound.28: snd_soc_register_card() failed: -517
[    5.440763] platform sound.28: Driver imx-ac97-vt1613 requests probe deferral
[    5.479050] VT1613 SoC Audio Codec [ID = 5649 - 4123]
[    5.483756] imx-ac97-vt1613 sound.28: vt1613-hifi-analog <-> 2028000.ssi mapping ok
[    5.483790] fsl-ssi-dai 2028000.ssi: ASoC: Failed to set DAI format: -22```
``````

Btw: this is my fsl_ssi.c file: https://github.com/SolidRun/linux-imx6-3.14/blob/linux-linaro-lsk-v3.14-mx6/sound/soc/fsl/fsl_ssi.c

**Comment by waynatali** [comment]
HI, it seems me some dai_link binding problem
Have a look at this part of machine driver:
imx_vt1613_dai.codec_name = dev_name(&codec_pdev->dev);
imx_vt1613_dai.cpu_dai_name = dev_name(&ssi_pdev->dev);
you have to check  parsing of the codec and ssi nodes from the device tree
file, is it ok?
Because it is not yet fsl_ssi.c driver issue( I mean the changes you did
not port to your kernel)

2015-06-12 19:51 GMT+02:00 Peter V. notifications@github.com:

**Comment by waynatali** [comment]
ok, now I can see some later feedback.
in your fsl_ssi.c file in ops: fsl_ssi_set_dai_fmt (machine driver calls this ops), there is no support for AC97 mode, so you see 
this error: fsl-ssi-dai 2028000.ssi: ASoC: Failed to set DAI format: -22` You miss cases in first and third switches, have a look again at my fsl_ssi.c

**Comment by vpeter4** [comment]
Seems this is just a little to much for me :( Don't understand how this code works so don't understand what is missing either.

**Comment by waynatali** [comment]
Hi, I will take a deeper look at your fsl_ssi.c later. Yes it is a little
bit different from mine

2015-06-13 9:00 GMT+02:00 Peter V. notifications@github.com:

**Comment by waynatali** [comment]
Hi Peter I have your fsl_ssi driver working in my kernel. I had modified it a little. I have tried to write the differences here, but it is going to be too messy. what is the better way to give you those differences?

**Comment by patrykk** [comment]
I'm working on 4.0 kernel now. Could you share your source code? I have some problems with regmaps.

**Comment by waynatali** [comment]
Hi Patryk. As I know in kernel 4.0 it's easier to implement regmap for ac97 codecs. I had made back-porting for regmap in my kernel  from kernel 4.0.4 So you do not need my source code for regmap implementation any more. I think for kernel 4.0  - my commit for fsl_ssi.c is ok, my machine driver is ok too, but my vt1613 codec driver you have to modify a little, just for reason of my regmap implementation , that is not appropriate for kernel 4.0 and also regarding ac97 device API - there are some differences in kernel 4.0. But I can suggest you to take a look at this codec driver in kernel 4.0, that is also ac97 codec: sound/soc/codecs/ad1980.c  You will see it is not so much to change in my codec driver to make it work in kernel 4.0

**Comment by vpeter4** [comment]
@waynatali: put diff or even whole file to http://pastebin.com/

**Comment by waynatali** [comment]
ok, it is done, you can find file here http://pastebin.com/1DVYYWeY

2015-06-15 8:47 GMT+02:00 Peter V. notifications@github.com:

**Comment by vpeter4** [comment]
Little better but not yet perfect. Needs more investigation.

```
[    7.258581] imx-ac97-vt1613 sound.28: ASoC: CODEC vt1613.27 not registered
[    7.258635] imx-ac97-vt1613 sound.28: snd_soc_register_card() failed: -517
[    7.258664] platform sound.28: Driver imx-ac97-vt1613 requests probe deferral
[    7.501458] VT1613 SoC Audio Codec [ID = 5649 - 4123]
[    7.509109] imx-ac97-vt1613 sound.28: vt1613-hifi-analog <-> 2028000.ssi mapping ok
```

**Comment by patrykk** [comment]
I couldnt reset device from codec level. When I comment out reset code i probe function I have got ID = 0000 - 0000. Problem probably related to clock in ssi.

**Comment by waynatali** [comment]
Hi Patryk Can you share your fsl_ssi .c? and also your codec driver .

2015-06-16 9:59 GMT+02:00 Patryk notifications@github.com:

**Comment by patrykk** [comment]
http://kowalczyk.ws/vt/

**Comment by waynatali** [comment]
Hi Patryk. in codec driver in probe function you have to comment
snd_soc_alloc_ac97_codec(codec); as it is already done in ac97 =
snd_soc_new_ac97_codec(codec);

2015-06-16 14:59 GMT+02:00 Patryk notifications@github.com:

**Comment by vpeter4** [comment]
@waynatali: seems the driver works for me. Thank you.
Still needs to investigate one small issue. Will post in a few days.

**Comment by waynatali** [comment]
Hi Peter I have your issue when I compile sound card drivers as module
only. it seems some ordering problem, the
codec dev is not registered yet when machine driver is calling it in probe
function

2015-06-16 20:47 GMT+02:00 Natalia Kovalenko waykovalenko@gmail.com:

**Comment by vpeter4** [comment]
Yes, I think it is something like that. But seems it gets registered little later. Will put some prints in file to see execution. But driver is working also in Kodi. So this issue is almost closed. Only one left (LVDS display).

**Comment by patrykk** [comment]
I have still that same problem:
11844.502769] vt1613-codec vt1613: Failed to reset: AC97 link error
[11844.562726] vt1613-codec vt1613: Failed to reset: AC97 link error
[11844.567541] Failed to reset VT1613: AC97 link error
[11844.571300] vt1613-codec vt1613: ASoC: failed to probe component -5
[11844.576352] imx-ac97-vt1613 sound: ASoC: failed to instantiate card -5
[11844.581682] imx-ac97-vt1613 sound: snd_soc_register_card() failed: -5
[11844.586863] imx-ac97-vt1613: probe of sound failed with error -5

**Comment by waynatali** [comment]
Hi Patryk,
I have just tried your fsl_ssi.c and vt1613 .c compiled in kernel 4.04.
Sound card works like in kernel 3.14.

2015-06-16 22:05 GMT+02:00 Patryk notifications@github.com:

**Comment by patrykk** [comment]
without any additional modifications ? Maybe its a problem in dts file.

**Comment by waynatali** [comment]
only snd_soc_alloc_ac97_codec(codec);  commented in probe function. The only things I can suppose that possibly you have some problem with pinctrls for ac97link_running, ac97link_reset, ac97link_warm_reset  in device tree, Something like when iomux requests a pin( for example for ac97link_reset pinctrl group), that one is already in use for some another group.

**Comment by patrykk** [comment]
When will you release qdl kernel ? I dont want release vt1613 before your official release. It will be better for you from business point of view.

**Comment by vpeter4** [comment]
So I put few prints in kernel (soc-core.c) and this is result

```
[    6.455283] imx-ac97-vt1613 sound.25: ASoC: CPU DAI 2028000.ssi registered
[    6.455304] imx-ac97-vt1613 sound.25: ASoC: CODEC vt1613.24 not registered
[    6.455366] imx-ac97-vt1613 sound.25: snd_soc_register_card() failed: -517
[    6.455389] platform sound.25: Driver imx-ac97-vt1613 requests probe deferral
[    6.539498] imx-ac97-vt1613 sound.25: ASoC: CPU DAI 2028000.ssi registered
[    6.539518] imx-ac97-vt1613 sound.25: ASoC: CODEC vt1613.24 registered
[    6.559095] VT1613 SoC Audio Codec [ID = 5649 - 4123]
[    6.570663] imx-ac97-vt1613 sound.25: vt1613-hifi-analog <-> 2028000.ssi mapping ok
```

or

```
[    6.456811] imx-ac97-vt1613 sound.25: ASoC: CPU DAI 2028000.ssi registered
[    6.456835] imx-ac97-vt1613 sound.25: ASoC: CODEC vt1613.24 not registered
[    6.456880] imx-ac97-vt1613 sound.25: snd_soc_register_card() failed: -517
[    6.456902] platform sound.25: Driver imx-ac97-vt1613 requests probe deferral
[    6.463794] imx-ac97-vt1613 sound.25: ASoC: CPU DAI 2028000.ssi registered
[    6.463817] imx-ac97-vt1613 sound.25: ASoC: CODEC vt1613.24 not registered
[    6.463847] imx-ac97-vt1613 sound.25: snd_soc_register_card() failed: -517
[    6.463868] platform sound.25: Driver imx-ac97-vt1613 requests probe deferral
[    6.643025] imx-ac97-vt1613 sound.25: ASoC: CPU DAI 2028000.ssi registered
[    6.643055] imx-ac97-vt1613 sound.25: ASoC: CODEC vt1613.24 registered
[    6.662380] VT1613 SoC Audio Codec [ID = 5649 - 4123]
[    6.670296] imx-ac97-vt1613 sound.25: vt1613-hifi-analog <-> 2028000.ssi mapping ok
```

Seems codec can't be registered first time. But at least it does later :)

**Comment by patrykk** [comment]
I have seen in other driver in function reset some iteration up to 10. There is a some crap in  alsa. Please check sound/soc/codecs/ad1980.c from 4.0.x kernel

**Comment by vpeter4** [comment]
Didn't helped. Still codec not registered first time.

**Comment by waynatali** [comment]
yes. I see. I have read a little about and  it seems that it is a normal
approach to probe later the driver if a resource it depends on is not
available yet

2015-06-17 20:40 GMT+02:00 Peter V. notifications@github.com:

**Comment by waynatali** [comment]
regarding release of the qdl kernel... I will address this question to UDOO team :-)

**Comment by ektor5** [comment]
haha, we're working on it! It still miss the bossac driver and little more
testing, but it's quite stable so far!
btw, great work for the audio driver!

2015-06-17 23:38 GMT+02:00 waynatali notifications@github.com:

> regarding release of the qdl kernel... I will address this question to
> UDOO team :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UDOOboard/linux_kernel/issues/2#issuecomment-112958538
> .

## 

Ettore Chimenti

Cell: 333-1754004
Skype: ektor-5

**Comment by patrykk** [comment]
@waynatali  btw. I still have that same problem on 4.0.4 kernel with replaced ssi and added only driver and changes only for sound in dts file.
@vpeter4 : where the problem was?

**Comment by vpeter4** [comment]
@patrykk, as you can see from my log vt1613 codec is not registered first time. Only on second or third time it succeed. But seems to be working well anyway.

**Comment by waynatali** [comment]
@patrykk: Can you share your dts, dtsi files. I would like to try dtb made with your files

**Comment by patrykk** [comment]
All changes are in repo: https://github.com/patrykk/linux-udoo

**Comment by waynatali** [comment]
@patrykk: correct this error in &ssi1
- ac97-gpios = <&gpio4 19 0 &gpio4 18 0 &gpio4 30 0>;
  - ac97-gpios = <&gpio4 19 0 &gpio4 18 0 &gpio2 30 0>;

**Comment by waynatali** [comment]
some mess with minus and plus above, so first line minus, second one plus

**Comment by vpeter4** [comment]
Seems this driver really can't work as module reliably. Now I can't get it to work anymore. Only when compiled in kernel works.
Anyone has any tip what I can fix to work as module 100% reliably?

**Comment by patrykk** [comment]
@waynatali: hah right, but  still that same. Hmm, I dont have idea ;)

**Comment by waynatali** [comment]
@patrykk: mmmh it was the only thing in your dts files that caused that problem for me, but just to be very very sure :) did you do that change clearly, because that  was  so little change and the compiler possibly did not fetch it in file... when I have some doubts about, I make an error in file to force compiler, just to not recompile all stuff  ;), if you know a better way...

**Comment by waynatali** [comment]
@vpeter4: regarding 100 % reliability... the problem that in case of loadable module building, as the machine driver has no dependency on codec driver, in file modules.dep you can see this output:
kernel/sound/soc/codecs/snd-soc-vt1613.ko: kernel/drivers/base/regmap/regmap-ac97.ko
kernel/sound/soc/fsl/snd-soc-imx-ac97-vt1613.ko: 
so, no dependency...
Now some tips I have just invented and tried ( just to have an idea, perhaps it is not so elegant solution ;))
in vt1613.c declare this stuff:
bool vt1613_modules_dep_ok = true;
EXPORT_SYMBOL_GPL(vt1613_modules_dep); 
than in vt1613h:
extern bool vt1613_modules_dep_ok;
than call it in machine probe function like so: 
if(vt1613_modules_dep_ok) {
        dev_dbg(&pdev->dev, "module dependency (codec module) ok!\n");
}
that trick does nothing , just creates that dependency we need.
so as result you do not see any more that "failed: -517" and if you check modules.dep file, you see this output:
kernel/sound/soc/codecs/snd-soc-vt1613.ko: kernel/drivers/base/regmap/regmap-ac97.ko
kernel/sound/soc/fsl/snd-soc-imx-ac97-vt1613.ko: kernel/sound/soc/codecs/snd-soc-vt1613.ko kernel/drivers/base/regmap/regmap-ac97.ko
At least for me that trick works :-)

**Comment by waynatali** [comment]
miss-print: EXPORT_SYMBOL_GPL(vt1613_modules_dep_ok); :-)

**Comment by vpeter4** [comment]
Yes, this helps loading module (no more error). Thank you.
But it is strange that sound works with using speaker-test. But Kodi doesn't see the analog output. Works only when build in kernel. Even more strange is that it was working few days back.

Is it possible to load module at very early stage from kernel itself and not from systemd/udev?

**Comment by vpeter4** [comment]
Any news about releasing this kernel? Can I commit vt1613 patch to openelec before that?

**Comment by patrykk** [comment]
Hi, Works for me as a module with kernel 4.0 :)

[  421.302889] VT1613 SoC Audio Codec [ID = 5649 - 4123]
[  421.308545] imx-ac97-vt1613 sound: vt1613-hifi-analog <-> 2028000.ssi mapping ok

**Comment by vpeter4** [comment]
For me also. But only speaker-test work - Kodi doesn't see the device. Don't know why not.

**Comment by patrykk** [comment]
probably will be better use : 

```
ret = request_module("snd-soc-vt1613");
        if (ret)
                dev_err(&pdev->dev, "request_module returned: %d\n", ret);
```

in `imx_vt1613_probe function`

**Comment by vpeter4** [comment]
Tested this and module is not even loaded.

**Comment by vpeter4** [comment]
I have another issue with this driver on my kernel - the volume is very, very low.
But today I noticed it was very much louder. But after reboot it was low again.

I checked with amixer and saw everything is fine. But if I set volume to 0 then
sound was louder. That's why I think this part in file sound/soc/codecs/vt1613.c is wrong

```
SOC_DOUBLE_TLV("PCM Playback Volume", AC97_PCM, 8, 0, 31, 0, mix_tlv),
```

I think invert parameter should be 1

```
SOC_DOUBLE_TLV("PCM Playback Volume", AC97_PCM, 8, 0, 31, 1, mix_tlv),
```

then it works as expected. Maybe this happens only on my kernel or maybe this is general problem.

**Comment by waynatali** [comment]
With alsamixer you can increase the volume. Run alsamixer and increase the
value of the Speaker's slider

2015-06-29 11:34 GMT+02:00 Peter V. notifications@github.com:

**Comment by vpeter4** [comment]
I clear old logs where this problem was more clear. But the problem was that volume has to be decreased to get louder. And it was already at 100%. That's why this invert thing helped me. And now it is always 100% loud at boot. No amixer settings needed.
Anyway, it works for me and already included in my images. Little to loud from start (70% would better) but no one complained. Seems no one is even using it.

**Comment by vpeter4** [comment]
In sound/soc/fsl/imx-ac97-vt1613.c#L101 must be changed to support dual too.
  if (!of_machine_is_compatible("udoo,imx6q-udoo") && !of_machine_is_compatible("udoo,imx6dl-udoo"))

**Comment by patrykk** [comment]
Hi, I tried integrate vt1613 driver with kernel 4.4:
https://github.com/patrykk/linux-udoo/commit/b3a9beaf7079ff502bc08c87cff6158343a39ef4
https://github.com/patrykk/linux-udoo/commit/dca15e2aba380cee058c744c5845d25658edca3c
https://github.com/patrykk/linux-udoo/commit/4feebd15a562201fc9cf7c42cb8c03d9e886b502

but I have got information about wron codec ID:
[   12.594041] VT1613 SoC Audio Codec [ID = 5649 - 5649]
[   12.606004] imx-ac97-vt1613 sound: vt1613-hifi-analog <-> 2028000.ssi mapping ok

do you know where could be a problem?

**Comment by vpeter4** [comment]
I'm using kernel from xbian https://github.com/xbianonpi/xbian-sources-kernel/tree/imx6-4.4.y
and this is ok (http://sprunge.us/QIOT). You can see my commits there regarding VT1613.

**Comment by patrykk** [comment]
Hi, I dont use functions like soc_ac97_dev_register and soc_ac97_dev_unregister and vt1613_reset so I dont need so big a interference with kernel source code. I'll introduce changes based on your ssi patch.

**Comment by patrykk** [comment]
ok, works: https://github.com/patrykk/linux-udoo/commit/4d393e3cb976206b8e58c3dbe0bfc738528cd9e0
I use my version of vt1613 driver.
