### ISSUE TITLE
No /dev/ttyMCC on UDOO Neo

### ISSUE THREAD

**Issue by cyrilfr** [UDOOboard/linux_kernel#27]
/dev/ttyMCC isn't available on UDOO Neo anymore.

**Comment by waltervl** [comment]
Can you explain more? I just checked with Udoobuntu 2.1 (latest image) and there it is still available.....

**Comment by cyrilfr** [comment]
Does it use the last revision of the kernel? Because I had to move back to https://github.com/UDOOboard/linux_kernel/commit/4640a64dfcb11486733d0abf460283a6d27030ba to make it work with OpenEmbedded. Otherwise, nothing appears in /dev/.

**Comment by graugans** [comment]
This [commit](https://github.com/UDOOboard/linux_kernel/commit/4e616eab54ea5192c14ea31f69630e5c72396b3c) seems to break stuff. The _CONFIG_ option `IMX_MCC_TTY` is renamed to `IMX_UDOONEO_MCC` So an update to the [NEO defconfig](https://github.com/graugans/meta-udoo/blob/krogoth/recipes-kernel/linux/linux-udooboard/udooneo/defconfig) should [fix](https://github.com/UDOOboard/linux_kernel/commit/67d8907c200bd062e39a1e3dfc68c9c564645fe1.patch) it.

**Comment by fmntf** [comment]
Hi. `/dev/ttyMCC` was named `m4_udooneo_debugger.c`, which was misleading. The file was renamed, so the Kconfig option. As @graugans pointed out, you just need to update your defconfig.

**Comment by cyrilfr** [comment]
@graugans Well thanks for pointing this out.
