### ISSUE TITLE
Pradeep process uses 80-90% CPU

### ISSUE THREAD

**Issue by gorghino** [UDOOboard/linux_kernel#30]
**Board:** Udoo Neo Full
**Kernel** : Linux 3.14.56-udooneo-02045-g45a88ad #6 SMP PREEMPT

**Note:** I fixed /drivers/tty/serial/imx.c in order to make UART6 works (http://www.udoo.org/forum/threads/a9-uart6-and-udoobuntu.3196/page-3) 

Hi guys,
At the moment I've a running sketch that reads from the sensors and write to the Serial.
At the same time a python script has opened the MCC Serial port in order to read the data.

Unfortunately I found that pradeep is using 80-90% CPU and the UDOO took 11500mAh in 18h :/
That means that we're far from a mobile use with a portable lithium battery. What we're aiming to do is to keep it alive at least 60/72h if it's possible.

Mr. Rovai on the forum (http://www.udoo.org/forum/threads/pradeep-process.6458/) told that the pradeep bug should be already fixed. So It's a python bug with UDOO's MCC? 
I even put a sleep in my reading loop in the python script without success.

Let me know if I have to attach sketch and/or python script.

**Comment by fmntf** [comment]
Fixed in 1dfc7ab3a83d872e7258f6c53d1a74c5b123de0f
Install the new kernel via apt-get.
