### ISSUE TITLE
GCC5 compatibility

### ISSUE THREAD

**Issue by patrykk** [UDOOboard/linux_kernel#4]
Hi,
"gcc5 changes the default standard to c11, which makes kernel build unhappy"
so we have to back port small patch from newer kernel:

https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/patch/?id=d6d25d1664a5751d200e469fe5027e7fc68b73c1

It should be pull request.

best regards,

**Comment by vpeter4** [comment]
But is it good for arm in general? I read somewhere that it is broken for arm arch.

**Comment by patrykk** [comment]
I use it on kernel 4.0. I'll make tests with 3.14.

**Comment by patrykk** [comment]
Do you have some links to informations about it?

**Comment by vpeter4** [comment]
Only by word of OpenELEC main dev.

**Comment by patrykk** [comment]
I dont have stability problems on 4.0 kernel but I dont know how it looks on 3.14. Now I use 3.14 with this patch and it looks ok. If I remember correct old gcc used gnu99 so nothing changed. They have many patches and guys from vanillla kernel changed the flags for all platforms.

**Comment by vpeter4** [comment]
Kernel is fine so it seems. But there are problems with other applications.
Anyway, I would not use fresh gcc on old kernel anyway. Until I need to. Still remember isues with some other gcc version I had.

**Comment by patrykk** [comment]
On arch linux ARM they use only one GCC and for now it is 5.1 so If we want push official kernel to arch and replace old 3.0 we have to support it. btw. If you use this patch It will not change anything for gcc 4 and 3.

**Comment by vpeter4** [comment]
So it is 5.1 too :)
Seems it is ok then (maybe having old info).

**Comment by patrykk** [comment]
We have to patch kernel for new GCC. Users from arch linux have a problem with compilation.

**Comment by sarnold** [comment]
Is this still an issue?  Neo builds fine for me with gcc-5.3.0 on gentoo and with meta-fsl/openembedded.  I haven't noticed anything weird on Gentoo but I only used 5.3 with crossdev (native uses 4.9.3).  Still waiting for poky image to finish but it's all built with 5.3.0.  Is there something in particular I can test?

**Comment by fmntf** [comment]
It has been fixed in 72d0b87e5db1dca09413582d6f6059e99d36b0f9

Edit: in any case for the moment supported GCC versions are 4.8 (for UDOObuntu) and 4.6 (for Android). Other kind of builds may work but it is not guaranteed.

**Comment by patrykk** [comment]
It's not that same problem.

**Comment by sarnold** [comment]
I just built a couple of neo images yesterday with a slightly hacked version of fsl-community-bsp (all with gcc-5.3.0) and it's all fine.  Switched it to master branch if anyone wants to try it:

https://github.com/VCTLabs/fsl-community-bsp-platform
